vich_uploader:
    db_driver: orm

    mappings:
        serie_image:
            uri_prefix: '%serie_image%'
            upload_destination: '%kernel.project_dir%/public%serie_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
